// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKPBIuwHy1nc1FGBhcnqdkiy0uTNbA1is',
    appId: '1:329336245312:web:1c5adb653460f6c91123a5',
    messagingSenderId: '329336245312',
    projectId: 'diet-picnic',
    authDomain: 'diet-picnic.firebaseapp.com',
    storageBucket: 'diet-picnic.firebasestorage.app',
    measurementId: 'G-F24MQ7249S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBrAmlZQRhinHHJq_wXv-B9n64rUeDI4',
    appId: '1:329336245312:android:bc2aa91b4e805dc31123a5',
    messagingSenderId: '329336245312',
    projectId: 'diet-picnic',
    storageBucket: 'diet-picnic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlFSIu5umS99pMNwN3DFYxle9LGacQN4E',
    appId: '1:329336245312:ios:d0048dd1f6a44f311123a5',
    messagingSenderId: '329336245312',
    projectId: 'diet-picnic',
    storageBucket: 'diet-picnic.firebasestorage.app',
    iosBundleId: 'com.mahmoudayman.dietPicnicClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlFSIu5umS99pMNwN3DFYxle9LGacQN4E',
    appId: '1:329336245312:ios:d0048dd1f6a44f311123a5',
    messagingSenderId: '329336245312',
    projectId: 'diet-picnic',
    storageBucket: 'diet-picnic.firebasestorage.app',
    iosBundleId: 'com.mahmoudayman.dietPicnicClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKPBIuwHy1nc1FGBhcnqdkiy0uTNbA1is',
    appId: '1:329336245312:web:449aa78cde6652731123a5',
    messagingSenderId: '329336245312',
    projectId: 'diet-picnic',
    authDomain: 'diet-picnic.firebaseapp.com',
    storageBucket: 'diet-picnic.firebasestorage.app',
    measurementId: 'G-HKB21FTMD9',
  );

}
